version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      plex-on-the-go:
        aliases:
            - elasticsearch

  keycloak:
    image: jboss/keycloak
    ports:
      - "4664:8080"
    networks:
      plex-on-the-go:
        aliases:
            - keycloak
    environment:
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: "keycloak"

  frontend:
    build: frontend
    hostname: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      plex-on-the-go:
        aliases:
            - frontend

  backend:
    build: backend
    hostname: backend
    ports:
      - "8888:8080"
    depends_on:
      - elasticsearch
    networks:
      plex-on-the-go:
        aliases:
            - backend

networks:
  plex-on-the-go:
    driver: bridge
