version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      plex-on-the-go:
        aliases:
            - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - plex-on-the-go
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601:5601"
    networks:
      - plex-on-the-go
    depends_on:
      - elasticsearch

  keycloak:
    image: jboss/keycloak
    ports:
      - "4664:8080"
    networks:
      plex-on-the-go:
        aliases:
            - keycloak
    environment:
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: "keycloak"

  frontend:
    build: frontend
    hostname: frontend
    ports:
      - "4200:4200"
    networks:
      plex-on-the-go:
        aliases:
            - frontend

  backend:
    build: backend
    hostname: backend
    ports:
      - "8080:8080"
    networks:
      plex-on-the-go:
        aliases:
            - backend

networks:
  plex-on-the-go:
    driver: bridge
