version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - plex-on-the-go

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - plex-on-the-go
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601:5601"
    networks:
      - plex-on-the-go
    depends_on:
      - elasticsearch

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    ports:
      - "4664:8080"
    networks:
      - plex-on-the-go
    environment:
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: "keycloak"

networks:
  plex-on-the-go:
    driver: bridge