version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      plex-on-the-go:
        aliases:
            - elasticsearch

  keycloak:
    build: keycloak
    ports:
      - "4664:8080"
    environment:
      - DB_VENDOR=H2
      - PROXY_ADDRESS_FORWARDING=false
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
    networks:
      plex-on-the-go:
        aliases:
            - keycloak

networks:
  plex-on-the-go:
    driver: bridge
